host Draft 4 RFC's
(Re)add Draft 4 version of

* json-schema-core.html
* json-schema-hypermedia.html
* json-schema-validation.html

by reprocessing from XML versions via `xml2rfc $file --html`.

Unfortunately latest version of `xml2rfc` 2.5.2 throws
```
Parsing file draft-fge-json-schema-validation-00.xml
ERROR: Incomplete and out-of date <date/> element: <date year="2013"/>
Traceback (most recent call last):
  File "/usr/local/bin/xml2rfc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/xml2rfc/run.py", line 213, in main
    htmlwriter.write(filename)
  File "/usr/local/lib/python2.7/dist-packages/xml2rfc/writers/base.py", line 1261, in write
    self._format_date()
  File "/usr/local/lib/python2.7/dist-packages/xml2rfc/writers/base.py", line 523, in _format_date
    self.date = datetime.datetime.strptime(date.attrib['year']+date.attrib['month']+date.attrib.get('day','1'), '%Y%B%d')
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:73200)
KeyError: 'month'
```

So need to downgrade to version 2.5.1

The source XML files are from IETF:

* https://tools.ietf.org/id/draft-zyp-json-schema-04.xml
* https://tools.ietf.org/id/draft-fge-json-schema-validation-00.xml
* https://tools.ietf.org/id/draft-luff-json-hyper-schema-00.xml

There MD5 hashes are:
```
3481e2ad9170b83d94c27182563f9296  draft-fge-json-schema-validation-00.xml
cce284011213170b2eccb3a4436bec32  draft-luff-json-hyper-schema-00.xml
8c0a495a45777faf8df95b5fd80e3ac8  draft-zyp-json-schema-04.xml
```

Need to apply this patch to `draft-luff-json-hyper-schema-00.xml`
```
--- draft-luff-json-hyper-schema-00.xml.1       2013-02-01 03:35:00.000000000 +0100
+++ draft-luff-json-hyper-schema-00.xml 2017-02-22 16:41:14.495199666 +0100
@@ -1032,7 +1032,7 @@
                     <author initials="F." surname="Galiegue">
                     </author>

-                    <author initials="K."surname="Zyp">
+                    <author initials="K." surname="Zyp">
                         <organization>SitePen (USA)</organization>
                     </author>
```
in order to fix this error thrown by `xml2rfc`:
```
WARNING: Parsing Error: attributes construct error, line 1035, column 42
ERROR: Unable to parse the XML document: draft-luff-json-hyper-schema-00.xml
 draft-luff-json-hyper-schema-00.xml: Line 1035: attributes construct error
 draft-luff-json-hyper-schema-00.xml: Line 1035: Couldn't find end of Start Tag author
 draft-luff-json-hyper-schema-00.xml: Line 1035: attributes construct error
 draft-luff-json-hyper-schema-00.xml: Line 1035: Couldn't find end of Start Tag author line 1035
 draft-luff-json-hyper-schema-00.xml: Line 1037: Opening and ending tag mismatch: front line 1030 and author
 draft-luff-json-hyper-schema-00.xml: Line 1042: Opening and ending tag mismatch: reference line 1029 and front
 draft-luff-json-hyper-schema-00.xml: Line 1043: Opening and ending tag mismatch: references line 1008 and reference
 draft-luff-json-hyper-schema-00.xml: Line 1044: Opening and ending tag mismatch: back line 1006 and references
 draft-luff-json-hyper-schema-00.xml: Line 1127: Opening and ending tag mismatch: rfc line 21 and back
 draft-luff-json-hyper-schema-00.xml: Line 1128: Extra content at the end of the document
```